name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pixi
        uses: prefix-dev/setup-pixi@v0.5.1
      - name: Format and lint
        run: |
          pixi run fmt
          pixi run lint     
      - name: Test recipe schema
        run: |
          pixi run test
      - name: Assert no changes
        run: |
          git diff --exit-code