# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]  

permissions:
  contents: read


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: setup-pixi
        uses: prefix-dev/setup-pixi
        with:
          pixi-version: v0.22.0
          cache: true
          auth-host: prefix.dev
          auth-token: ${{ secrets.PREFIX_DEV_TOKEN }}
      - run: pixi run test
      - name: Format and lint
        run: |
          pixi run fmt
          pixi run lint 
      - name: Assert no changes
        run: |
            git diff --exit-code     
      - name: Test
        run: |
          pixi run coverage      
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

